### ISSUE TITLE
Should the `JettyWebContainerService` has a higher priority than the `JerseyRestService` ?

### ISSUE THREAD

**Issue by iskey** [apache/karaf-minho#41]
It seems that the `JettyWebContainerService` should have a higher priority than `JerseyRestService`.

On the `Ubuntu 22.04.1 LTS` distribution, I got this error.

```
2023-01-17 14:56:21 INFO   org.apache.karaf.minho.boot.service.ServiceRegistry add Adding minho-rest-service service (1000)
Exception in thread "main" java.lang.IllegalStateException: Can't register minho-rest-service
	at org.apache.karaf.minho.boot.service.ServiceRegistry.add(ServiceRegistry.java:88)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.apache.karaf.minho.boot.Minho.start(Minho.java:58)
	at org.apache.karaf.minho.boot.Main.main(Main.java:63)
Caused by: java.lang.IllegalStateException: minho-http-service is not found in the service registry
	at org.apache.karaf.minho.rest.jersey.JerseyRestService.onRegister(JerseyRestService.java:52)
	at org.apache.karaf.minho.boot.service.ServiceRegistry.add(ServiceRegistry.java:86)
	... 12 more

```

**Comment by iskey** [comment]
Sorry, I saw it is duplicated with #38, I will try to clear my local maven repo and try again.

**Comment by iskey** [comment]
The release [minho-0.1](https://github.com/apache/karaf-minho/releases/tag/minho-0.1) is still in the wrong state. 
The `SNAPSHOT` one works fine for me. I will close this issue.

**Comment by jbonofre** [comment]
Yes I fixed that already for 0.2. I will cut the release soon.

**Comment by iskey** [comment]
@jbonofre, thanks, it will be great. ^v^

**Comment by jbonofre** [comment]
I have a couple of other fixes to do.
